update to latest main

diff --git a/.github/workflows/nomad.yaml b/.github/workflows/nomad.yaml
--- a/.github/workflows/nomad.yaml
+++ b/.github/workflows/nomad.yaml
@@ -2,6 +2,8 @@ name: "Run performance tests on Nomad cluster"
 
 on:
   workflow_dispatch:
+  schedule:
+    - cron: "0 0 * * 4" # Run Nomad workflow at 00:00 on Thursdays
 
 concurrency:
   group: ${{ github.workflow }}
@@ -60,6 +62,7 @@ jobs:
               else
                   echo -n "."
               fi
+              sleep 5
           done
           echo "done"
 
@@ -74,14 +77,60 @@ jobs:
           echo "download-url=$DOWNLOAD_URL" >> "$GITHUB_OUTPUT"
 
       - name: Run Nomad Job
+        id: run-nomad-job
         env:
           NIXPKGS_ALLOW_UNFREE: 1
           NOMAD_ADDR: https://nomad-server-01.holochain.org:4646
           NOMAD_CACERT: "${{ github.workspace }}/nomad/server-ca-cert.pem"
           NOMAD_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
           NOMAD_VAR_scenario-url: ${{ steps.get-download-url.outputs.download-url }}
-          NOMAD_VAR_run-id: ${{ github.run_id }}
+          NOMAD_VAR_run-id: "${{ matrix.job-name || matrix.scenario-name }}_${{ github.run_id }}"
+          RUN_ID: "${{ matrix.job-name || matrix.scenario-name }}_${{ github.run_id }}"
         run: |-
-          nix run --impure --inputs-from . nixpkgs#nomad -- job run nomad/jobs/${{ matrix.job-name || matrix.scenario-name }}.nomad.hcl
+          set -euo pipefail
+          nomad_output=$(nix run --impure --inputs-from . nixpkgs#nomad -- job run nomad/jobs/${{ matrix.job-name || matrix.scenario-name }}.nomad.hcl)
+          echo "$nomad_output"
+          echo "Ran ${{ matrix.job-name || matrix.scenario-name }} with run ID ${RUN_ID}" >> "$GITHUB_STEP_SUMMARY"
+          alloc_ids=$(echo "$nomad_output" | grep -oP --color=never 'Allocation "\K[0-9a-f]+(?=" created)' | paste -sd ' ' -)
+          if [ -z "$alloc_ids" ]; then
+            echo "Failed to extract allocation IDs from Nomad job output"
+            exit 1
+          fi
 
-          echo "Ran ${{ matrix.job-name }} with run ID ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
+          echo "alloc_ids=$alloc_ids" >> "$GITHUB_OUTPUT"
+
+      - name: Save alloc_ids to file
+        run: |
+          for alloc_id in ${{ steps.run-nomad-job.outputs.alloc_ids }}; do
+            echo "${{ matrix.job-name || matrix.scenario-name }},${alloc_id}" >> alloc_ids.csv
+          done
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: alloc_ids_${{ matrix.job-name || matrix.scenario-name }}
+          path: alloc_ids.csv
+
+  wait-for-all-jobs:
+    name: Wait for all jobs to finish
+    runs-on: [self-hosted, wind-tunnel]
+    needs: run-scenarios
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/download-artifact@v4
+        with:
+          path: ./alloc_ids
+
+      - name: Wait for all jobs
+        env:
+          NOMAD_ADDR: https://nomad-server-01.holochain.org:4646
+          NOMAD_CACERT: "${{ github.workspace }}/nomad/server-ca-cert.pem"
+          NOMAD_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
+        run: |-
+          cat ./alloc_ids/*/alloc_ids.csv > all_alloc_ids.csv
+          while IFS= read -r line; do
+            scenario_name=$(echo "$line" | cut -d',' -f1)
+            alloc_id=$(echo "$line" | cut -d',' -f2)
+            echo "Waiting for $scenario_name with allocation ID $alloc_id"
+            nix develop --command ./nomad/wait_for_jobs.sh $scenario_name $alloc_id
+          done < all_alloc_ids.csv
